### ISSUE TITLE
[Suggestion] Start, Stop, And Restart Buttons

### ISSUE THREAD

**Issue by MuhsinunCool** [rymate1234/JPanel#11]
The title says it all. Can u add them? They would be extremely helpful! Thanks!

**Comment by Bayside308** [comment]
As the plugin requires the server to be online to function, a start and restart button likely wouldn't work, unless you've configured a restart server properly.

**Comment by MuhsinunCool** [comment]
I don't think the start button wud be possible but i think the restart and stop buttons wud be possible correct?

**Comment by Bayside308** [comment]
Restart is only possible if you configure a start.sh or start.bat in the
spigot.yml, or if you have another script checking constantly to see if the
server is down. A stop button is possible, and start is not.

**Comment by rymate1234** [comment]
A start button is completely impossible, you'd need the JPanel instance to run separately from the server, and as the whole point of JPanel is that it's implemented as a plugin for bukkit I will not be able to add a start button.

As @Bayside308 mentioned, Restarts are only possible if a start.sh or start.bat file is specified in the spigot.yml, and since not all servers will be running on Spigot, creating a restart button that relies on this is not something I intend to do.

There's already a way to stop the server from JPanel - the stop command in the console. If you want admins to be able to stop the server but not run all commands, I have some ideas on how to implement this, specifically a command whitelist so JPanel users can run some, but not all, commands.
