### ISSUE TITLE
[Bug] Files Not Generating

### ISSUE THREAD

**Issue by MuhsinunCool** [rymate1234/JPanel#19]
Title says it all. The files in the JPanel_Public (I believe that's the name) folder do not generate with JPanel Beta 6 or 7. That's pretty much all there is to it. There is an error in the console:

`[22:22:02 INFO]: [JPanel] Enabling JPanel v1.0-SNAPSHOT
[22:22:02 WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"
.
[22:22:02 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[22:22:02 WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder f
or further details.
[22:22:02 INFO]: [JPanel] JPanel enabled!`

When I go to the web page I can't see the log and the ram and CPU usage and stuff is just constantly loading. When I go to the files tab, there's nothing there. The files that are supposed to generate in the folder in the root folder of the server didn't generate on my computer, but they did generate on my host.

Please fix this ASAP! Also, I made a YouTube review video of this plugin. This was an issue that was present during the making of that video. I believe JPanel Beta 4.3 and 4.2 DID work though.

EDIT: FOUND A FIX FOR U M8!!! Unfortunately, it's on ur end. U need to update this dependency. It's called SLF4J: http://www.slf4j.org/download.html. Thanks for reading! And PLEASE FIX ASAP!!! :D

**Comment by MuhsinunCool** [comment]
Bump! Edited and found a fix for u m8! Unfortunately, u have to fix it for us! :D

**Comment by MuhsinunCool** [comment]
Bump again! I seriously NEED this plugin! Please fix ASAP!!! D: <3 m8!

**Comment by MuhsinunCool** [comment]
Here's the msg i'm getting:
`[17:18:19] [Server thread/INFO]: [JPanel] Enabling JPanel v1.0-SNAPSHOT
[17:18:19] [Server thread/WARN]: log4j:WARN No appenders could be found for logger (spark.staticfiles.StaticFilesConfiguration).
[17:18:19] [Server thread/WARN]: log4j:WARN Please initialize the log4j system properly.
[17:18:19] [Server thread/INFO]: [JPanel] JPanel enabled!`

**Comment by MuhsinunCool** [comment]
@rymate1234 Mind checking out this post? please?

**Comment by rymate1234** [comment]
I've seen it and am currently trying to make a jar file that includes the slf4j logger stuff (that isn't related to your main issue, but might be useful for debugging), however I'm encountering build errors

**Comment by MuhsinunCool** [comment]
@rymate1234 alr thx wud that fix my issue??? Cuz my thing just won't even start. It doesn't work wen i go to localhost:4567 :/

**Comment by rymate1234** [comment]
No, I need more information to solve the problem, which is why I'm adding the the slf4j dependency.

Let me reiterate: **the slf4j error is not the issue - it just stops some stuff being logged**

Once the build is fixed, you'll be able to download debug builds with the dependency from [http://rymatemc.co.uk/jenkins/job/JPanel/](http://rymatemc.co.uk/jenkins/job/JPanel/). Release builds on bukkitdev will not include it

**Comment by rymate1234** [comment]
Found the issue - the method to extract the resources from the jar file did not work when there was spaces in the filename.

Build 10 in the jenkins has the permanent fix, however I'm in the process of recoding the front end styling so I do not recommend using those builds for now.

Until then, the easiest thing you can do is to simply eliminate all spaces in your server folders - i.e instead of 
> C:\Users\User\Desktop\InfiniD Ware Network\Main Server\
Rename the folders so it's 
> C:\Users\User\Desktop\InfiniD_Ware_Network\Main_Server\
